package p25

import (
	"bytes"
	"testing"
)

// bytesToBlockBits expands 12 bytes to 96 MSB-first bits.
func bytesToBlockBits(b [12]byte) []uint8 {
	out := make([]uint8, 96)
	for i := 0; i < 12; i++ {
		for j := 0; j < 8; j++ {
			out[i*8+j] = (b[i] >> uint(7-j)) & 1
		}
	}
	return out
}

// synthPDUPayload builds the status-bearing dibit payload for a PDU with the
// given header block and data blocks. Header gets a valid CRC-16; the data
// blocks' final 4 bytes are overwritten with the CRC-32 over data blocks.
func synthPDUPayload(header [12]byte, data [][12]byte) []Dibit {
	blks := byte(len(data))
	header[6] = (header[6] &^ 0x7f) | (blks & 0x7f)

	hbits := bytesToBlockBits(header)
	appendTSBKCRC(hbits)

	// Compute CRC-32 over all data blocks minus the trailing 4 CRC bytes.
	var flat []byte
	for _, d := range data {
		flat = append(flat, d[:]...)
	}
	if len(flat) >= 4 {
		c := crc32P25(flat, (len(flat)-4)*8)
		flat[len(flat)-4] = byte(c >> 24)
		flat[len(flat)-3] = byte(c >> 16)
		flat[len(flat)-2] = byte(c >> 8)
		flat[len(flat)-1] = byte(c)
	}

	var enc []uint8
	enc = append(enc, trellisEncode(hbits)...)
	for i := 0; i < len(data); i++ {
		var blk [12]byte
		copy(blk[:], flat[i*12:i*12+12])
		enc = append(enc, trellisEncode(bytesToBlockBits(blk))...)
	}
	return buildPayloadWithStatus(enc)
}

func TestParsePDU_SingleHeaderPlusData(t *testing.T) {
	// fmt=0x15 (unconfirmed MBT), sap=0x3d(61), mfid=0x90, llid=0x0179A6.
	header := [12]byte{0x15, 0x3d, 0x90, 0x01, 0x79, 0xa6, 0x00, 0x00, 0, 0, 0, 0}
	data := [][12]byte{
		{0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66},
	}
	payload := synthPDUPayload(header, data)

	pdu := parsePDU(payload)
	if pdu == nil {
		t.Fatal("parsePDU returned nil")
	}
	if !pdu.HeaderCRCOK {
		t.Error("HeaderCRCOK = false, want true")
	}
	if pdu.Format != 0x15 {
		t.Errorf("Format = 0x%02x, want 0x15", pdu.Format)
	}
	if pdu.SAP != 0x3d {
		t.Errorf("SAP = 0x%02x, want 0x3d", pdu.SAP)
	}
	if pdu.MFID != 0x90 {
		t.Errorf("MFID = 0x%02x, want 0x90", pdu.MFID)
	}
	if pdu.LLID != 0x0179a6 {
		t.Errorf("LLID = 0x%06x, want 0x0179a6", pdu.LLID)
	}
	if pdu.BlocksToFollow != 1 {
		t.Errorf("BlocksToFollow = %d, want 1", pdu.BlocksToFollow)
	}
	if !pdu.PayloadCRCOK {
		t.Error("PayloadCRCOK = false, want true")
	}
	if len(pdu.Payload) != 12 {
		t.Fatalf("len(Payload) = %d, want 12", len(pdu.Payload))
	}
	// First 8 bytes are application data; last 4 are the CRC-32 (not checked here).
	wantHead := []byte{0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff, 0x11, 0x22}
	for i, w := range wantHead {
		if pdu.Payload[i] != w {
			t.Errorf("Payload[%d] = 0x%02x, want 0x%02x", i, pdu.Payload[i], w)
		}
	}
}

func TestParsePDU_RejectsCorruptHeader(t *testing.T) {
	header := [12]byte{0x15, 0x3d, 0x90, 0x01, 0x79, 0xa6, 0x00, 0x00, 0, 0, 0, 0}
	data := [][12]byte{{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}}
	payload := synthPDUPayload(header, data)
	// Flip 20 consecutive non-status dibits in the header block region.
	// A single-bit flip would be silently corrected by the Viterbi decoder;
	// 20 dibits (40 bit errors) far exceeds the trellis correction capacity,
	// guaranteeing that the decoded header bytes are scrambled and the CRC-16
	// residue is non-zero.
	count := 0
	for i := range payload {
		if isStatusPosition(i) {
			continue
		}
		payload[i] ^= 0x3
		count++
		if count >= 20 {
			break
		}
	}
	pdu := parsePDU(payload)
	if pdu == nil {
		t.Fatal("parsePDU returned nil unexpectedly (full payload supplied)")
	}
	if pdu.HeaderCRCOK {
		t.Fatal("expected header CRC to fail on corruption")
	}
}

// crc32P25 over a known buffer. Vector generated by running op25's crc32()
// (p25p1_fdma.cc:71) over the 4 bytes {0x12,0x34,0x56,0x78} treated as 32 bits.
// Python reference:
//
//	def crc32_p25(buf, lenBits):
//	    g = 0x04c11db7
//	    crc = 0
//	    for i in range(lenBits):
//	        b = (buf[i // 8] >> (7 - (i % 8))) & 1
//	        crc <<= 1
//	        if ((crc >> 32) ^ b) & 1:
//	            crc ^= g
//	    return (crc & 0xffffffff) ^ 0xffffffff
//
// Output: 0xe771a8af
func TestCRC32P25_KnownVector(t *testing.T) {
	got := crc32P25([]byte{0x12, 0x34, 0x56, 0x78}, 32)
	want := uint32(0xe771a8af)
	if got != want {
		t.Fatalf("crc32P25 = 0x%08x, want 0x%08x", got, want)
	}
}

// Second known vector exercising the partial-byte path (lenBits not a
// multiple of 8). Same Python reference as above: crc32_p25([0xAB,0xCD], 12)
// -> 0x5d7734b8.
func TestCRC32P25_PartialByte(t *testing.T) {
	got := crc32P25([]byte{0xAB, 0xCD}, 12)
	want := uint32(0x5d7734b8)
	if got != want {
		t.Fatalf("crc32P25 = 0x%08x, want 0x%08x", got, want)
	}
}

func TestProcessFrame_PDUEmitsControlFrame(t *testing.T) {
	header := [12]byte{0x15, 0x3d, 0x90, 0x01, 0x79, 0xa6, 0x00, 0x00, 0, 0, 0, 0}
	data := [][12]byte{{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}}
	payload := synthPDUPayload(header, data)

	d := NewP25Decoder(25000)
	f := Frame{NID: NID{NAC: 0x171, DUID: 0xC}, Payload: payload}
	_, cfs := d.processFrame(f)

	var pduFrame *ControlFrame
	for i := range cfs {
		if cfs[i].PDU != nil {
			pduFrame = &cfs[i]
		}
	}
	if pduFrame == nil {
		t.Fatal("no ControlFrame with PDU set")
	}
	if pduFrame.DUID != 0xC || pduFrame.NAC != 0x171 {
		t.Errorf("NAC/DUID = 0x%x/0x%x, want 0x171/0xC", pduFrame.NAC, pduFrame.DUID)
	}
	if !pduFrame.PDU.HeaderCRCOK || pduFrame.PDU.LLID != 0x0179a6 {
		t.Errorf("PDU not decoded: crc=%v llid=0x%06x", pduFrame.PDU.HeaderCRCOK, pduFrame.PDU.LLID)
	}
}

// A DUID-0xC frame whose payload is too short to form a header block must
// dispatch cleanly: parsePDU returns nil, so the ControlFrame carries PDU=nil
// (mirroring how a malformed TDUlc yields LC=nil) - no panic.
func TestProcessFrame_PDUNilPayloadSafe(t *testing.T) {
	d := NewP25Decoder(25000)
	f := Frame{NID: NID{NAC: 0x171, DUID: 0xC}, Payload: make([]Dibit, 10)}
	_, cfs := d.processFrame(f)

	found := false
	for i := range cfs {
		if cfs[i].DUID == 0xC {
			found = true
			if cfs[i].PDU != nil {
				t.Errorf("expected nil PDU for too-short payload, got %+v", cfs[i].PDU)
			}
		}
	}
	if !found {
		t.Fatal("no ControlFrame emitted for DUID 0xC")
	}
}

// TestParsePDU_FullHeaderFieldExtraction locks the bit-layout mapping for
// every PDUHeader field. Each field is set with a unique value and the
// recovered values are compared. This test is the only test in Phase 2 that
// nails down the byte-offset/bit-shift formulas for Confirmed, Outbound,
// PadOctets, Synchronize, PacketSeq, FragmentSeq, and DataHeaderOffset - if
// it passes, every later task can trust the field accessors blindly.
func TestParsePDU_FullHeaderFieldExtraction(t *testing.T) {
	// Build a header with a unique, recognizable value in every field.
	//   header[0] bit 1 = Confirmed = 1
	//   header[0] bit 2 = Outbound  = 0  (inbound)
	//   header[0] bits 3..7 = Format = 0x16 (PACKET_DATA = 22)
	//   header[1] bits 2..7 = SAP    = 0x04 (PACKET_DATA SAP)
	//   header[2]            = MFID  = 0x90
	//   header[3..5]         = LLID  = 0x0179a6
	//   header[6] bits 1..7  = blks  = 3
	//   header[7] bits 3..7  = pad   = 5  (bottom 5 bits of byte)
	//   header[8] bit 0      = Sync  = 1  (MSB)
	//   header[8] bits 1..2  = PacketSeq    = 2
	//   header[8] bits 3..5  = FragmentSeq  = 5
	//   header[9] bits 2..7  = DataHeaderOffset = 2 (per sdrtrunk: 2 bytes => SN-DATA header lives in first 16 bits)
	header := [12]byte{
		// byte 0: 0_1_0_10110  = 0x56  (reserved=0|conf=1|out=0|fmt=10110)
		0x56,
		// byte 1: 00_000100      = 0x04  (reserved=00|sap=000100)
		0x04,
		0x90,             // byte 2: MFID
		0x01, 0x79, 0xa6, // bytes 3..5: LLID
		// byte 6: 0_0000011  = 0x03  (full-msg-flag=0|blks=3)
		0x03,
		// byte 7: 000_00101  = 0x05  (reserved=000|pad=5)
		0x05,
		// byte 8: 1_10_101_00 = 0xD4  (sync=1|pktSeq=10=2|fragSeq=101=5|reserved=00)
		0xD4,
		// byte 9: 00_000010  = 0x02  (reserved=00|hdrOff=000010=2)
		0x02,
		0x00, 0x00, // CRC slot, set by appendTSBKCRC
	}
	// We synthesize a PDU with this header and 3 data blocks (matches blks=3).
	data := [][12]byte{
		{0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66},
		{0x10, 0x20, 0x30, 0x40, 0x50, 0x60, 0x70, 0x80, 0x90, 0xa0, 0xb0, 0xc0},
		{0xde, 0xad, 0xbe, 0xef, 0x01, 0x02, 0x03, 0x04, 0, 0, 0, 0}, // last 4 = CRC slot
	}
	payload := synthPDUPayload(header, data)

	pdu := parsePDU(payload)
	if pdu == nil || !pdu.HeaderCRCOK {
		t.Fatalf("header CRC failed: pdu=%+v", pdu)
	}
	if !pdu.Confirmed {
		t.Errorf("Confirmed = false, want true")
	}
	if pdu.Outbound {
		t.Errorf("Outbound = true, want false")
	}
	if pdu.Format != 0x16 {
		t.Errorf("Format = 0x%02x, want 0x16", pdu.Format)
	}
	if pdu.SAP != 0x04 {
		t.Errorf("SAP = 0x%02x, want 0x04", pdu.SAP)
	}
	if pdu.MFID != 0x90 {
		t.Errorf("MFID = 0x%02x, want 0x90", pdu.MFID)
	}
	if pdu.LLID != 0x0179a6 {
		t.Errorf("LLID = 0x%06x, want 0x0179a6", pdu.LLID)
	}
	if pdu.BlocksToFollow != 3 {
		t.Errorf("BlocksToFollow = %d, want 3", pdu.BlocksToFollow)
	}
	if pdu.PadOctets != 5 {
		t.Errorf("PadOctets = %d, want 5", pdu.PadOctets)
	}
	if !pdu.Synchronize {
		t.Errorf("Synchronize = false, want true")
	}
	if pdu.PacketSequence != 2 {
		t.Errorf("PacketSequence = %d, want 2", pdu.PacketSequence)
	}
	if pdu.FragmentSequence != 5 {
		t.Errorf("FragmentSequence = %d, want 5", pdu.FragmentSequence)
	}
	if pdu.DataHeaderOffset != 2 {
		t.Errorf("DataHeaderOffset = %d, want 2", pdu.DataHeaderOffset)
	}
}

// TestFrameSync_PDUMultiBlock_ConfirmedRoundTrip is the regression for the
// "SNDCP only records 3 blocks" bug. P25 Phase 1 PDUs (DUID 0xC) are
// variable-length: the FrameSync used to emit a fixed 424-dibit payload
// (= 1 header + 3 data blocks), so any confirmed-mode PDU with
// BlocksToFollow > 3 was truncated -- header+payload CRCs failed and the
// IPv4 datagram was unreadable. After the two-stage header-peek fix in
// FrameSync, payloadCap is extended to (1+blks)*pduBlockBits non-status bits,
// and all blocks reach parsePDU.
//
// Exercise the former ceiling plus values across the complete 7-bit range:
// 16, 17, 32, and 127 blocks.
func TestFrameSync_PDUMultiBlock_ConfirmedRoundTrip(t *testing.T) {
	for _, nBlocks := range []int{16, 17, 32, 127} {
		t.Run("blks="+itoa(nBlocks), func(t *testing.T) {
			// Build a confirmed PACKET_DATA PDU whose reassembled payload is
			// nBlocks*16 bytes. SN-DATA(2) + user(...) + pad(0) + CRC-32(4)
			// fills the rest exactly so PayloadCRCOK can be verified.
			payloadBytes := nBlocks * 16
			pl := make([]byte, payloadBytes)
			pl[0] = 0x45 // PDUType=4, NSAPI=5
			pl[1] = 0x00
			for i := 2; i < payloadBytes-4; i++ {
				pl[i] = byte((i * 7) & 0xff)
			}
			c := crc32P25(pl, (payloadBytes-4)*8)
			pl[payloadBytes-4] = byte(c >> 24)
			pl[payloadBytes-3] = byte(c >> 16)
			pl[payloadBytes-2] = byte(c >> 8)
			pl[payloadBytes-1] = byte(c)

			// header[0]=0x16 (PACKET_DATA), header[7]=pad=0,
			// header[9]=0x02 (DataHeaderOffset=2).
			header := [12]byte{0x16, 0x04, 0x90, 0x01, 0x79, 0xa6,
				byte(nBlocks) & 0x7f, 0, 0, 0x02, 0, 0}
			blocks := make([][16]byte, nBlocks)
			for i := 0; i < nBlocks; i++ {
				copy(blocks[i][:], pl[i*16:(i+1)*16])
			}

			// Wrap the PDU dibit payload in a sync + NID stream so it goes
			// through FrameSync (where the bug lives).
			pduPayload := synthConfirmedPDU(header, blocks)
			var stream []Dibit
			stream = append(stream, syncWord[:]...)
			stream = append(stream, buildNIDStream(0x171, 0xC)...)
			stream = append(stream, pduPayload...)
			// Trailing zeros so the last data dibit doesn't collide with EOF
			// before the cap is reached. Use dibit 0 (never appears in the
			// sync word) to avoid a false mid-payload resync.
			for i := 0; i < 200; i++ {
				stream = append(stream, 0)
			}

			fs := NewFrameSync()
			frames := fs.Feed(stream)
			if len(frames) != 1 {
				t.Fatalf("got %d frames, want 1 (FrameSync truncated the PDU)", len(frames))
			}
			f := frames[0]
			if f.NID.DUID != 0xC {
				t.Fatalf("DUID=0x%X, want 0xC", f.NID.DUID)
			}

			d := NewP25Decoder(25000)
			_, cfs := d.processFrame(f)
			var pf *ControlFrame
			for i := range cfs {
				if cfs[i].PDU != nil {
					pf = &cfs[i]
					break
				}
			}
			if pf == nil {
				t.Fatal("processFrame: no ControlFrame with PDU")
			}
			if !pf.PDU.HeaderCRCOK {
				t.Fatalf("HeaderCRCOK=false (frame still truncated upstream?)")
			}
			if int(pf.PDU.BlocksToFollow) != nBlocks {
				t.Fatalf("BlocksToFollow=%d, want %d", pf.PDU.BlocksToFollow, nBlocks)
			}
			if pf.PDU.ConfirmedCRC9OK != nBlocks {
				t.Errorf("ConfirmedCRC9OK=%d, want %d (some blocks did not reach parsePDU)",
					pf.PDU.ConfirmedCRC9OK, nBlocks)
			}
			if !pf.PDU.PayloadCRCOK {
				t.Errorf("PayloadCRCOK=false (multi-block CRC-32 needs all %d blocks)", nBlocks)
			}
			if len(pf.PDU.Payload) != payloadBytes {
				t.Errorf("len(Payload)=%d, want %d", len(pf.PDU.Payload), payloadBytes)
			}
			if got, want := pf.PDU.Payload, pl; !bytes.Equal(got, want) {
				t.Fatalf("Payload mismatch for %d blocks: got %d bytes, want %d", nBlocks, len(got), len(want))
			}
			if got, want := len(f.Payload), pduPayloadDibits(nBlocks); got != want {
				t.Fatalf("frame payload dibits=%d, want %d", got, want)
			}
		})
	}
}

// TestFrameSync_PDUHeaderCRCFail_ColdSync_Drops verifies that on the very
// first sync of a stream (cold sync, syncCount transitioning 0 -> 1), a
// DUID-0xC frame whose header peek fails its trellis CRC is DROPPED rather
// than emitted at the legacy 424-dibit cap. This is the cold-start defence:
// noise lead-in lets SymbolRecovery's PLL settle into a wrong attractor that
// produces 32 dibits which BCH-decode to the local NAC by luck (4096 NACs * 7
// DUIDs occupy enough of the BCH(63,16) codeword space that distance <=11 is
// achievable on noise). Emitting the resulting "blks=42 hdrCRC=false" junk
// PDU misleads downstream parsing and consumes ~96 ms of dibit stream that
// could carry a real later burst. See the cold-start sensitivity memo and
// data/sndcp-uplink-analysis-20260617 for the live evidence.
func TestFrameSync_PDUHeaderCRCFail_ColdSync_Drops(t *testing.T) {
	const nBlocks = 6
	payloadBytes := nBlocks * 16
	pl := make([]byte, payloadBytes)
	pl[0] = 0x45
	for i := 1; i < payloadBytes; i++ {
		pl[i] = byte((i * 7) & 0xff)
	}
	header := [12]byte{0x16, 0x04, 0x90, 0x01, 0x79, 0xa6, byte(nBlocks), 0, 0, 0x02, 0, 0}
	blocks := make([][16]byte, nBlocks)
	for i := 0; i < nBlocks; i++ {
		copy(blocks[i][:], pl[i*16:(i+1)*16])
	}
	pduPayload := synthConfirmedPDU(header, blocks)
	// Trash the first ~25 non-status dibits past trellis correction.
	corrupted := 0
	for i := 0; i < len(pduPayload) && corrupted < 25; i++ {
		if isStatusPosition(i) {
			continue
		}
		pduPayload[i] ^= 0x3
		corrupted++
	}

	var stream []Dibit
	stream = append(stream, syncWord[:]...)
	stream = append(stream, buildNIDStream(0x171, 0xC)...)
	stream = append(stream, pduPayload...)
	for i := 0; i < 200; i++ {
		stream = append(stream, 0)
	}

	fs := NewFrameSync()
	frames := fs.Feed(stream)
	if len(frames) != 0 {
		t.Fatalf("got %d frames, want 0 (cold-sync peek-fail should be dropped)", len(frames))
	}
	if fs.ColdPeekRejects != 1 {
		t.Errorf("ColdPeekRejects=%d, want 1", fs.ColdPeekRejects)
	}
}

// TestFrameSync_PDUHeaderCRCFail_WarmSync_FallsBackToLegacyCap verifies that
// after at least one frame has already been admitted (syncCount > 1), the
// peek-fail fallback to the legacy 424-dibit cap still applies. A
// header-CRC-failed frame in this regime is on a marginal but real signal
// (the second sync uses syncThresh=4, not the cold threshold), so emitting
// the partial frame surfaces the SNR problem to the caller.
func TestFrameSync_PDUHeaderCRCFail_WarmSync_FallsBackToLegacyCap(t *testing.T) {
	// Build two back-to-back frames: a clean 4-block PDU first (pduPayloadDibits(4)
	// ~505 > legacy 424, so the cap extends to fit the actual frame and the next
	// sync isn't absorbed via mid-payload resync), then a 6-block PDU with a
	// corrupted header to exercise the warm-sync peek-fail fallback path.
	cleanHeader := [12]byte{0x16, 0x04, 0x90, 0x01, 0x79, 0xa6, 0x04, 0, 0, 0x02, 0, 0}
	cleanBlocks := make([][16]byte, 4)
	for i := range cleanBlocks {
		for j := range cleanBlocks[i] {
			cleanBlocks[i][j] = byte((i*16 + j) ^ 0x55)
		}
	}
	cleanPayload := synthConfirmedPDU(cleanHeader, cleanBlocks)

	const nBlocks = 6
	pl := make([]byte, nBlocks*16)
	pl[0] = 0x45
	for i := 1; i < len(pl); i++ {
		pl[i] = byte((i * 7) & 0xff)
	}
	corruptHeader := [12]byte{0x16, 0x04, 0x90, 0x01, 0x79, 0xa6, byte(nBlocks), 0, 0, 0x02, 0, 0}
	corruptBlocks := make([][16]byte, nBlocks)
	for i := 0; i < nBlocks; i++ {
		copy(corruptBlocks[i][:], pl[i*16:(i+1)*16])
	}
	corruptPayload := synthConfirmedPDU(corruptHeader, corruptBlocks)
	corrupted := 0
	for i := 0; i < len(corruptPayload) && corrupted < 25; i++ {
		if isStatusPosition(i) {
			continue
		}
		corruptPayload[i] ^= 0x3
		corrupted++
	}

	var stream []Dibit
	stream = append(stream, syncWord[:]...)
	stream = append(stream, buildNIDStream(0x171, 0xC)...)
	stream = append(stream, cleanPayload...)
	stream = append(stream, syncWord[:]...)
	stream = append(stream, buildNIDStream(0x171, 0xC)...)
	stream = append(stream, corruptPayload...)
	for i := 0; i < 200; i++ {
		stream = append(stream, 0)
	}

	fs := NewFrameSync()
	frames := fs.Feed(stream)
	if len(frames) != 2 {
		t.Fatalf("got %d frames, want 2 (clean + warm-peek-fail-at-legacy-cap)", len(frames))
	}
	if got, want := len(frames[1].Payload), payloadLen(0xC); got != want {
		t.Errorf("payload len=%d, want %d (legacy cap on warm peek-fail)", got, want)
	}
	if fs.ColdPeekRejects != 0 {
		t.Errorf("ColdPeekRejects=%d, want 0 (warm peek-fail should NOT be cold-rejected)", fs.ColdPeekRejects)
	}
}

// itoa is a local helper to avoid importing strconv just for subtest names.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var buf [12]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}

func TestViterbiDecodeRaw_ReturnsBitsRegardlessOfCRC(t *testing.T) {
	// Build a 12-byte block with a valid CRC-16 (last 16 bits) via the same
	// recipe the TSBK synthesis uses, encode through the trellis, decode raw.
	var bits [96]uint8
	bits[0], bits[5], bits[20] = 1, 1, 1 // arbitrary payload pattern
	appendTSBKCRC(bits[:])               // makes crcCCITT16(12 bytes)==0
	enc := trellisEncode(bits[:])

	out, crcOK := viterbiDecodeRaw(enc)
	if !crcOK {
		t.Fatal("expected CRC-16 OK for a well-formed block")
	}
	if len(out) != 96 {
		t.Fatalf("len(out)=%d, want 96", len(out))
	}
	for i := range bits {
		if out[i] != bits[i] {
			t.Fatalf("bit %d: got %d want %d", i, out[i], bits[i])
		}
	}

	// Corrupt the CRC region: bits still returned, crcOK false.
	bits[80] ^= 1
	enc2 := trellisEncode(bits[:])
	out2, crcOK2 := viterbiDecodeRaw(enc2)
	if crcOK2 {
		t.Fatal("expected CRC-16 to fail after corruption")
	}
	if len(out2) != 96 {
		t.Fatalf("len(out2)=%d, want 96 even on CRC fail", len(out2))
	}
}
