package p25

import (
	"encoding/binary"
	"encoding/hex"
	"math"
	"os"
	"strings"
	"testing"
)

type pcmMetrics struct {
	RMSDelta float64
	MaxDelta float64
	SNRDB    float64
	Corr     float64
}

func comparePCM(a, b [160]float32) pcmMetrics {
	var sumA, sumB, sumAB, sumErr, maxErr float64
	for i := range a {
		af := float64(a[i])
		bf := float64(b[i])
		err := af - bf
		sumA += af * af
		sumB += bf * bf
		sumAB += af * bf
		sumErr += err * err
		if math.Abs(err) > maxErr {
			maxErr = math.Abs(err)
		}
	}
	rmsErr := math.Sqrt(sumErr / float64(len(a)))
	snr := 120.0
	if sumErr > 0 {
		snr = 10 * math.Log10(sumA/sumErr)
	}
	corr := 1.0
	if sumA > 0 && sumB > 0 {
		corr = sumAB / math.Sqrt(sumA*sumB)
	}
	return pcmMetrics{RMSDelta: rmsErr, MaxDelta: maxErr, SNRDB: snr, Corr: corr}
}

func requirePCMClose(t *testing.T, got, want [160]float32) {
	t.Helper()
	m := comparePCM(got, want)
	if m.Corr < 0.995 || m.SNRDB < 35 || m.RMSDelta > 350 || m.MaxDelta > 3000 {
		t.Fatalf("PCM mismatch: corr=%.6f snr=%.2f rms_delta=%.2f max_delta=%.2f",
			m.Corr, m.SNRDB, m.RMSDelta, m.MaxDelta)
	}
}

func TestComparePCMIdentical(t *testing.T) {
	var pcm [160]float32
	for i := range pcm {
		pcm[i] = float32(i - 80)
	}
	requirePCMClose(t, pcm, pcm)
}

func TestComparePCMRejectsInverted(t *testing.T) {
	var a, b [160]float32
	for i := range a {
		a[i] = float32(i - 80)
		b[i] = -a[i]
	}
	m := comparePCM(a, b)
	if m.Corr >= 0.995 {
		t.Fatalf("corr = %.6f, want rejected", m.Corr)
	}
}

// TestVocoderPCMRegression is a REAL regression test (replaces the dead
// requirePCMClose(t, pcm, pcm) no-op). It decodes a frozen IMBE input
// codeword and asserts the PCM output matches a frozen golden snapshot
// within drift tolerances (corr>=0.995, snr>=35, rms_delta<=350, max_delta<=3000).
//
// This is a SELF-SNAPSHOT: the golden was generated by THIS decoder's current
// output (see vocoder_pcm_gen_test.go). It is NOT cross-decoder ground truth
// (two MBE decoders synthesize different absolute samples, so cross-decoder
// PCM comparison is invalid). The test catches unintended PCM output drift.
func TestVocoderPCMRegression(t *testing.T) {
	// Read input hex (88-bit IMBE codeword, 11 bytes)
	inHex, err := os.ReadFile("testdata/vocoder/imbe_input.hex")
	if err != nil {
		t.Fatalf("read input hex: %v", err)
	}
	raw, err := hex.DecodeString(strings.TrimSpace(string(inHex)))
	if err != nil {
		t.Fatalf("decode input hex: %v", err)
	}
	if len(raw) != 11 {
		t.Fatalf("input hex decoded to %d bytes, want 11", len(raw))
	}

	// Unpack to 88-bit codeword
	var codeword [88]uint8
	for i := 0; i < 11; i++ {
		for j := 0; j < 8; j++ {
			bitIdx := i*8 + j
			if bitIdx < 88 {
				codeword[bitIdx] = (raw[i] >> uint(7-j)) & 1
			}
		}
	}

	// Decode via root IMBE decoder
	dec := NewIMBEDecoder()
	defer dec.Close()
	got, errs := dec.Decode(codeword, 0)
	_ = errs // allow any error count, we're freezing whatever the decoder produces

	// Read golden PCM (160 float32, 640 bytes, little-endian)
	goldenBytes, err := os.ReadFile("testdata/vocoder/imbe_golden.pcm")
	if err != nil {
		t.Fatalf("read golden pcm: %v", err)
	}
	if len(goldenBytes) != 640 {
		t.Fatalf("golden pcm size = %d, want 640", len(goldenBytes))
	}
	var want [160]float32
	for i := 0; i < 160; i++ {
		bits := binary.LittleEndian.Uint32(goldenBytes[i*4:])
		want[i] = math.Float32frombits(bits)
	}

	// Assert PCM matches golden within drift tolerances
	requirePCMClose(t, got, want)
}
